<?php

return [
    'INTRA' => [
        'driver'        => 'oracle',
        'tns'           => env('DB_TNS', ''),
        'host'          => '12.123.28.2',
        'port'          => '1521',
        'database'      => 'ORCLMJ',
        'username'      => 'intramitra',
        'password'      => 'identifiedbyme',
        'charset'       => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'        => env('DB_PREFIX', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
        'edition'       => env('DB_EDITION', 'ora$base'),
        'server_version'=> env('DB_SERVER_VERSION', '11g'),
    ],
    'MITRA' => [
        'driver'        => 'oracle',
        'tns'           => env('DB_TNS', ''),
        'host'          => '12.123.28.2',
        'port'          => '1521',
        'database'      => 'ORCLMJ',
        'username'      => 'MITRA',
        'password'      => 'mitra',
        'charset'       => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'        => env('DB_PREFIX', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
        'edition'       => env('DB_EDITION', 'ora$base'),
        'server_version'=> env('DB_SERVER_VERSION', '11g'),
    ],
    'SEHATI' => [
        'driver'        => 'oracle',
        'tns'           => env('DB_TNS', ''),
        'host'          => '12.123.28.2',
        'port'          => '1521',
        'database'      => 'ORCLMJ',
        'username'      => 'SEHATI',
        'password'      => 'sehati',
        'charset'       => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'        => env('DB_PREFIX', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
        'edition'       => env('DB_EDITION', 'ora$base'),
        'server_version'=> env('DB_SERVER_VERSION', '11g'),
    ],
    'JAYA' => [
        'driver'        => 'oracle',
        'tns'           => env('DB_TNS', ''),
        'host'          => '12.123.28.2',
        'port'          => '1521',
        'database'      => 'ORCLMJ',
        'username'      => 'JAYA',
        'password'      => 'jaya',
        'charset'       => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'        => env('DB_PREFIX', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
        'edition'       => env('DB_EDITION', 'ora$base'),
        'server_version'=> env('DB_SERVER_VERSION', '11g'),
    ],
    'MAJU' => [
        'driver'        => 'oracle',
        'tns'           => env('DB_TNS', ''),
        'host'          => '12.123.28.2',
        'port'          => '1521',
        'database'      => 'ORCLMJ',
        'username'      => 'MAJU',
        'password'      => 'maju',
        'charset'       => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'        => env('DB_PREFIX', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
        'edition'       => env('DB_EDITION', 'ora$base'),
        'server_version'=> env('DB_SERVER_VERSION', '11g'),
    ],
];
